# Generated by Django 3.2.8 on 2021-10-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211008_0846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedOrders',
        ),
    ]
