# Generated by Django 3.2.8 on 2021-10-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_completedorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='accounts.Customer'),
        ),
    ]
